apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llb-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Replace with your fork/remote if different
    repoURL: https://github.com/msohail22/low-level-lab.git
    targetRevision: HEAD
    path: infra/k8s/root-app
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
