apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llb-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/msohail22/low-level-lab.git
    targetRevision: HEAD
    path: infra/k8s/apps/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: llb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llb-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/msohail22/low-level-lab.git
    targetRevision: HEAD
    path: infra/k8s/apps/redis
  destination:
    server: https://kubernetes.default.svc
    namespace: llb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llb-kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/msohail22/low-level-lab.git
    targetRevision: HEAD
    path: infra/k8s/apps/kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: llb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llb-reactor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/msohail22/low-level-lab.git
    targetRevision: HEAD
    path: infra/k8s/apps/reactor
  destination:
    server: https://kubernetes.default.svc
    namespace: llb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
